import DiscordConnection from "./DiscordConnection.js";

class InviteGenerator {
    /** @type {InviteGenerator|null} */
    static #instance = null;

    static getInstance() {
        if (this.#instance === null) {
            this.#instance = new InviteGenerator();
        }

        return this.#instance;
    }

    async generateInvite() {
        return DiscordConnection.getInstance().generateInvite(
            process.env.GUILD_ID,
            process.env.CHANNEL_ID,
            {
                maxUses: 1,
                unique: true,
                reason: 'Generated by the Express.js server',
            }
        );
    }
}

export default InviteGenerator;
